baseURL = "https://christykl.github.io/"
languageCode = "en-us"
title = "Brave New World"
theme = ["PaperMod"]

ShowReadingTime = true
ShowBreadCrumbs = true

[params]
  math = true  # Enable math support
  
  [params.homeInfoParams]
    Title = "Welcome to Brave New World"
    Content = "Hey there, this is Christy! You're visiting my personal blog where I document my self-learning and projects (mostly relating to deep learning/computer vision at the moment), as well as write about cool ideas and books I come across."
  
  [[params.socialIcons]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/christykl"
  
  [[params.socialIcons]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/christykl/"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true  # This allows HTML in Markdown