baseURL = "https://christykl.github.io/"
languageCode = "en-us"
title = "Brave New World"
theme = ["PaperMod"]

[params]
  [params.HomeInfoParams]
    Title = "Welcome to Brave New World"
    Content = "Hey there, this is Christy! You're visiting my personal blog where I document my self-learning and projects (mostly relating to deep learning/computer vision at the moment), as well as write about cool ideas and books I come across."
  
  [[params.SocialIcons]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/christykl"
  
  [[params.SocialIcons]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/christykl/"
  
  ShowReadingTime = true
  ShowBreadCrumbs = true
  enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
